name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Diagnostics (tree + versions)
        run: |
          echo "=== TREE (depth 3) ==="
          find . -maxdepth 3 -type f | sort
          echo "=== Python ==="
          python -V
          python -c "import sys, os; print('CWD:', os.getcwd()); print('PYTHONPATH:', os.environ.get('PYTHONPATH'))"
      - name: Ruff (lint)
        run: ruff check .
      - name: Tests
        run: pytest -q
